server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
  multipart:
    max-file-size: 10MB
    max-require-size: 10MB
  message: i18n/message
  endcoding: UTF-8
  default-locale: en

api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30day 30*24*60*60
  secretKey: eaeF046zKIoyUmlCVJukLQQyhRfFanpwsKVZ0KfCUWs=